name: MachineLearning_SC
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - seaborn
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - ruff
  - pytest
  - opencv
  - pip:
    - python-dotenv
    - pynput
    - pyautogui
    - playsound
    - simpleaudio
    - torch
    #- paddlepaddle-gpu==3.2.0 -i https://www.paddlepaddle.org.cn/packages/stable/cu129/
    #- paddleocr