name: machinelearning_sc
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - ruff
  - pytest
  - pip:
    - python-dotenv
    - pynput
    - pyautogui
    - playsound
    - simpleaudio